#+TITLE: Primary Emacs Config
#+AUTHOR: Cole Neville
#+EMAIL: primary@coleneville.com
#+OPTIONS: num:nil

This gets packaged into ./config.el by org-babel-eval-in-repl imported by the init.el.

** Package Definitions

*** Package Auto Update

Automatic package updating, I am trying this out... Things may break...

#+BEGIN_SRC emacs-lisp
  (use-package auto-package-update
    :ensure t
    :custom
    (auto-package-update-delete-old-versions t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe))
#+END_SRC

*** Modus Theme Config and Setup

Setup the theme using the modus theme that is built in but using a use-package block to download a more recent version.
Customization is very minimal just removing the border on the mode-line and setting the base background to a dark grey
over the black.

#+BEGIN_SRC emacs-lisp
  (use-package modus-themes
    :ensure t
    :custom
    (modus-themes-common-palette-overrides
     `((border-mode-line-active bg-mode-line-active)
       (border-mode-line-inactive bg-mode-line-inactive)))
    (modus-vivendi-palette-overrides
     `((bg-main "#161616")))
    :config
      (load-theme 'modus-vivendi t))
#+END_SRC

*** Which Key

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :commands (which-key-mode)
    :bind (("M-h" . which-key-show-top-level))
    :custom
    (which-key-idle-delay 0.5))
#+END_SRC

*** Ace Window

#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :ensure t
    :bind (("C-x S" . ace-window)))
#+END_SRC

*** Docker

#+BEGIN_SRC emacs-lisp
  (use-package docker :ensure t)

#+END_SRC

*** Magit (Git Integration)

#+BEGIN_SRC emacs-lisp
  (use-package magit :ensure t)
#+END_SRC

*** VTerm

#+BEGIN_SRC emacs-lisp
  (use-package vterm :ensure t)
#+END_SRC

*** Ledger Mode

#+BEGIN_SRC emacs-lisp
  (use-package ledger-mode
    :ensure t
    :hook ((ledger-mode . flymake-mode)
	   (ledger-mode . display-line-numbers-mode)))

#+END_SRC

*** Nix Mode

#+BEGIN_SRC emacs-lisp
  (use-package nix-mode :ensure t)
#+END_SRC

*** Dockerfile Mode
#+BEGIN_SRC emacs-lisp
  (use-package dockerfile-mode :ensure t)
#+END_SRC
*** Docker Compose Mode

#+begin_src emacs-lisp
  (use-package docker-compose-mode
    :ensure t
    :commands (docker-compose-mode))
#+end_src

*** Robe (Enhanced Ruby Mode)

#+begin_src emacs-lisp
  (use-package robe
    :ensure t
    :hook (ruby-mode . robe-mode))
#+end_src

*** Rainbow Delimiters

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Company Mode (Code Completion)

#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :custom
    (company-tooltip-align-annotations t)
    (company-tooltip-display 'lines)
    (company-tooltip-flip-when-above t)
    (company-tooltip-margin 3)
    (company-tooltip-maximum-width 60)
    (company-frontends '(company-pseudo-tooltip-frontend
			 company-preview-if-just-one-frontend))
    :config
    (global-company-mode))
#+end_src

*** Counsel/Ivy (Searching)

#+begin_src emacs-lisp
  (use-package counsel
    :ensure t
    :commands (ivy-mode
	       counsel-mode)
    :custom
    (ivy-dynamic-exhibit-delay-ms 250)
    :bind (("C-f" . counsel-grep)
	   ("C-s" . counsel-git-grep)))
#+end_src

*** Treemacs (Left Side Directory Tree)

#+begin_src emacs-lisp
  (use-package treemacs
    :ensure t
    :commands (treemacs)
    :custom
    (treemacs-width 45)
    :config
    (treemacs-follow-mode 1)
    (treemacs-git-commit-diff-mode 1))
#+end_src

*** Org Roam

This is not loaded in the initial load of emacs and is instead deferred to key bind.

#+begin_src emacs-lisp
  (use-package org-roam
    :ensure t
    :custom
    (org-roam-directory "~/notes")
    :commands (org-roam-setup)
    :bind (("C-c n l" . org-roam-buffer-toggle)
	   ("C-c n f" . org-roam-node-find)
	   ("C-c n i" . org-roam-node-insert))
    :config
    (org-roam-setup))
#+end_src

*** Marginalia

#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :config
    (marginalia-mode))
#+end_src

*** Tree Sitter

#+begin_src emacs-lisp
  (use-package tree-sitter
    :ensure t
    :config
    (global-tree-sitter-mode)
    (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))

  (use-package treesit-auto
    :ensure t
    :config
    (global-treesit-auto-mode))
#+end_src

*** Eglot

#+begin_src emacs-lisp
  (use-package eglot :ensure t)
#+end_src

*** Aphelia (Code Formatting)

#+begin_src emacs-lisp
  (use-package apheleia
    :ensure t
    :commands (apheleia-global-mode))
#+end_src

*** Terraform

#+begin_src emacs-lisp
  (use-package terraform-mode :ensure t)
#+end_src

*** Editor Config

#+begin_src emacs-lisp
  (use-package editorconfig :ensure t)
#+end_src

** Main Config

*** Setting Variables (not for packages)

#+BEGIN_SRC emacs-lisp
  (setq visible-bell t
	ring-bell-function 'ignore)

  (setq inhibit-startup-screen t
	inhibit-startup-message t)

  (setq display-line-numbers-minor-tick 5
	  display-line-numbers-major-tick 25
	  display-line-numbers-width 4)

  (setq org-support-shift-select t)


  ;; This is required for eglot to load in cases where the folder is not a git repo
  (add-to-list 'project-vc-extra-root-markers "tsconfig.json")
#+END_SRC

*** Enable/Disable Minor Modes

#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (tab-bar-mode -1)
  (line-number-mode -1)

  (menu-bar-mode 1)

  (ivy-mode 1)
  (counsel-mode 1)
  (which-key-mode 1)
  (apheleia-global-mode 1)

  ;; Load treemacs last so ivy and counsel are setup
  (treemacs 1)

  (add-hook 'prog-mode-hook 'flymake-mode)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+END_SRC

*** Keybinds

#+begin_src emacs-lisp
  (global-set-key (kbd "C-z") 'ignore)
  (global-set-key (kbd "C-x C-z") 'ignore)
#+end_src
